MOV AH,35H
MOV AL,09H
INT 21H
MOV WORD PTR _oldISR[0],BX
MOV WORD PTR _oldISR[2],ES

MOV AH,35H
MOV AL,16H
INT 21H
MOV WORD PTR _chkISR[0],BX
MOV WORD PTR _chkISR[2],ES

LEA DX,hookBIOS ;set up first isr
MOV CX,CS
MOV DS,CX
MOV AX,15H
MOV AL,09H
INT 21H